### ISSUE TITLE
HelloThere tumbnails not showing

### ISSUE THREAD

**Issue by twMat** [NoteSelf/NoteSelf.github.io#15]
On https://noteself.github.io/online/ I noticed the HelloThere tiddler doesn't show the thumbnails.

So I did a search for `HelloThumbnail - Introduction Video` - it is there, as a shadow, and you can cick to open it but you also get this:

![image](https://cloud.githubusercontent.com/assets/4534056/25171621/c13911ca-24ee-11e7-8875-e3ecd5e5df81.png)

Interestingly, that tiddler is a shadow tiddler on https://noteself.github.io/online/
...but it is a standard tiddler on tiddlywiki.com

**Comment by danielo515** [comment]
I don't know why that tiddlers exist. The fact that it is a shadow tiddler is even weirder . Are you sure that it is not part of your configuration? If it is not, it's definitely a bug. However it does not appear on my personal wiki when I use the online version .

**Comment by twMat** [comment]
Um, just maybe it is my own configuration - from a long time ago. 

That's the third or fourth "I'm sorry" from me today ;-)

**Comment by danielo515** [comment]
> That's the third or fourth "I'm sorry" from me today ;-)

Never be sorry. Your additions to the repo are always of good quality :blink:
