### ISSUE TITLE
Feature Request: diff between revisions

### ISSUE THREAD

**Issue by christofbuerger** [NoteSelf/NoteSelf.github.io#23]
would be VERY cool to have the opportunity to select two revisions and getting displayed a diff comparable to source display here in github.
just an idea :-)

thank you for maintaining noteself. it is great!!

**Comment by danielo515** [comment]
Yes, it's something that I want to implement.
I think​it may be possible with just wiki text, at least for the basic one .
Glad you like Noteself !

**Comment by danielo515** [comment]
I just want to mention that I just added an UI to easily restore revisions. Not what you requested, but I thought you may be interested. I'm going to migrate this 8sdue to danielo515/tiddlypouch where it will be implemented

**Comment by danielo515** [comment]
@christofbuerger  the latest Version includes this feature. Maybe it does not make it on the best way, but it's quite useful in it's current state

Regards
