### ISSUE TITLE
Download + starting = direct error

### ISSUE THREAD

**Issue by twMat** [NoteSelf/NoteSelf.github.io#25]
On https://noteself.github.io/
...clicking download to save file
...clicking to open/start it...
the big LOADING letters show up, but they keep on flicking and the loading never ends.

Attempting to look at the Inspector tool (it flashesalso - I'm guessing the page is attempting to reload each flash) it says under "Console": *It failed to open indexedDB. Are you in private browsing mode?* (No I'm not)

**Comment by danielo515** [comment]
Browser version + OS ?

**Comment by twMat** [comment]
Ah, sorry: Win10 Chrome
I succeed with FF.

**Comment by danielo515** [comment]
That's weird ,
I tried with the same combination and it works for me. Which version of chrome ? Could you please inspect the developer tools ? F12 on windows

**Comment by twMat** [comment]
Latest version (58.0.3029.81 , 64-bit)
And it was via the inspector tools that I noted what I wrote in the post above. It is difficult to inspect though because the whole page reloads at every flash and so does the inspector. But is there any particular tab you want me to try to inspect?

**Comment by twMat** [comment]
Maybe this helps:

![image](https://cloud.githubusercontent.com/assets/4534056/25559446/b302c46c-2d3a-11e7-9878-01a0ae4a2d1b.png)

**Comment by danielo515** [comment]
Hello @twMat ,

Several things has changed since this issue was opened. It stills happens ?

**Comment by twMat** [comment]
Tried it and get this. New issue?

Win10, Chrome latest

![image](https://user-images.githubusercontent.com/4534056/35411561-82202ee8-0219-11e8-90c0-fd7a9ebb318b.png)

**Comment by danielo515** [comment]
Hello, thanks for your feedback.
Those bugs can be significant or be nothing. If you just ignore them does it work? This mean that you can create and save tiddlers and that after reloading they are not lost. 
Regards

**Comment by twMat** [comment]
Does not seem to work properly. Regarless if I click the garbage can icons on them, I get new similar popups when clicking "+" for new tiddler and then two more when saving tiddler.

So no misunderstanding; The file is a local one, that I got by going to
https://noteself.github.io/
...clicking download to save file
...clicking to open/start it.

Could it be something wrong with my computer? Maybe my uBlock origin chrome extension blocks some critical cookie or something? Maybe my Win10 settings to block the Win10 "spying tools" (key logging etc) is not good for NS?

![image](https://user-images.githubusercontent.com/4534056/35452880-6e5e327e-02c8-11e8-97a4-2a135d595bfe.png)

**Comment by danielo515** [comment]
It may be some security configuration of your computer. Does it happen on the online version too?

**Comment by twMat** [comment]
No, seems to work well in online version.

**Comment by danielo515** [comment]
With some of the latest enhacements this should not be longer an issue.
