### ISSUE TITLE
Attaching CouchDB database results in "Uncaught TypeError: e.logger is not a function"

### ISSUE THREAD

**Issue by thmarti** [NoteSelf/NoteSelf.github.io#36]
`(index):264 Injecting  0  startup tiddlers into tw
$:/core/modules/utils/logger.js:30 TiddlyPouch:config: Initializing config module
$:/core/modules/utils/logger.js:30 TiddlyPouch:config: Persist config to DB - OK Object
$:/core/modules/utils/logger.js:30 TiddlyPouch:config: Configuration startup finished Object
$:/core/modules/utils/logger.js:30 PouchStartup: Client side dbs created
$:/core/modules/utils/logger.js:30 DbStore:TestNotebook: Index skinny_tiddlers exists already
$:/core/modules/utils/logger.js:30 DbStore:TestNotebook: Index startup_tiddlers exists already
$:/core/modules/utils/logger.js:30 DbStore:TestNotebook: Error getting tiddler $:/DefaultTiddlers from DB n
$:/core/modules/utils/logger.js:30 PouchStartup: Error retrieving StoryList or DefaultTiddlers
$:/core/modules/utils/logger.js:30 PouchStartup: Client side dbs initialized

noteself.github.io/ Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

noteself.github.io/:9422 Uncaught TypeError: e.logger is not a function
$tw.utils.error @ noteself.github.io/:9422
$:/plugins/danielo515/tiddlypouch/pouchadaptor.js:13 Uncaught TypeError: e.logger is not a function
    at Object.o [as callback] ($:/plugins/danielo515/tiddlypouch/pouchadaptor.js:13:1432)
    at XMLHttpRequest.n.onreadystatechange ($:/plugins/danielo515/tiddlypouch/pouchadaptor.js:13:641)

$:/core/modules/utils/logger.js:30 syncer-browser: Dispatching 'save' task: $:/StoryList`

**Comment by danielo515** [comment]
@thmarti thanks for reporting this bug. Because you're using the production version the error trace is not much useful. Could you please try to reproduce the issue on the development version?  https://noteSelf.github.io/dev

Many thanks

**Comment by thmarti** [comment]
I've created a PR over in the tiddlypouch project: https://github.com/danielo515/tiddlypouch/pull/79

**Comment by danielo515** [comment]
@thmarti ,
Online version of NoteSelf should include the fix. Please make sure to reload the page at least twice. Tiddlypouch version should be 0.22.2

Regards
