### ISSUE TITLE
What about size

### ISSUE THREAD

**Issue by guischmo** [NoteSelf/NoteSelf.github.io#37]
Hi, thanks for your amazing app !
Sorry I'm a little new to all this so could you help me understand this:

-So let's say that I am very pleased with the app and that I create a big fat wiki of about 1gb, with tons of pictures and stuff.
-Let's say I use cloudant to sync between machines, and my ipad, and my iphone.
-Does that mean that all those machines will download the full 1g of database in a local place?
-Does that mean that when i go to the wiki with a new machine it will first need to download 1gb of data before being usable?

thanks a lot !

**Comment by danielo515** [comment]
Hello @guischmo

Thank you for your interest. 

First of all, let me know that tiddlywiky (if you know about it) does not work very well with embedded images. Of course is possible to include them, but it is not usually a good idea. 
Without including images, it's very unlikely that you reach such size. 

In any case, synchronization happens lazily. This means that it is executed on the bacground and you don't meet to wait until it finishes. 
However your assumption is correct, the entire database will be synced  to every device
