### ISSUE TITLE
Shortcut to change DB

### ISSUE THREAD

**Issue by mauloop** [NoteSelf/NoteSelf.github.io#40]
Maybe the issue is not the right place to post this. I was in need of easily switch DB, without opening ControlPanel every time, especially while using it on my phone.

I added this to my sidebar list:

```
title: $:/mau/CustomNS/DBselect
caption: PouchDB
tags: $:/tags/SideBar

{{$:/plugins/danielo515/tiddlypouch/ui/database-name}}
{{$:/plugins/danielo515/tiddlypouch/ui/save-database-config}}
```
Maybe you can add it or something similar to the plugin.

Another question: any plan to add token authentication_

**Comment by danielo515** [comment]
Hello @mauloop 

I also noticed this problem, in fact there is an issue about this: danielo515/tiddlypouch#55

In any case, the current database appears as a link under the wiki name. If you click on it, it will open the control panel directly on the database selection part. It's far from ideal, but it's better than opening the control panel manually.

Your solution is close, but it's a bit rough. I would prefer a drop-down without any edition capabilities and automatically triggering the save mechanism when you select a different database. Feel free to improve your suggestion and make a Pull Request to the tiddlypouch repo if you find the time

**Comment by mauloop** [comment]
Close this one and continue on danielo515/tiddlypouch#55
