### ISSUE TITLE
Opening exported html results in Javascript error

### ISSUE THREAD

**Issue by CursingRabbit** [NoteSelf/NoteSelf.github.io#41]
Exporting the offline version of Notself to html and opening the exported html file results in an 'Internal Javascript error'. Refreshing the Chrome browser is not fixing the problem.

Interestingly, the exported html file is exactly 2000KB large, while the original 'empty.html' of the offline version is with 2136KB larger.

The online version of [https://noteself.github.io/online](url) was not running at the same time while trying to open the exported html.
Using Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

Exporting of the offline version into an html-file was announced in this TiddlyWiki Google Groups thread:
[https://groups.google.com/d/msg/tiddlywiki/8Uw-TaJYn1g/ngy6k1qjAQAJ](url)

> Now it is possible to properly save the wiki in html.
>  Previously, because the synchronous nature of the saving mechanism (and the async one of the syncer module) you may end with incomplete files (not containing all your tiddlers). 
> Now when you save the wiki we make sure that all the tiddlers are loaded
> Please note that for some reason this only works on the offline version. IT WILL NOT WORK ON THE ONLINE ONE

**Comment by danielo515** [comment]
Hello @CursingRabbit 

Good catch. I never tried to export the offline version. The difference in size you see is the absence of pouchdb library, which is mandatory.

Seems that something is bad with the save filter. I'm not sure if I should add the missing library or to entirely remove the TPouch thing when exporting.

Many thanks.
