### ISSUE TITLE
Can an existing TiddlyWiki be uploaded?

### ISSUE THREAD

**Issue by greatwillow** [NoteSelf/NoteSelf.github.io#45]
Just wondering if it's possible to upload an already made TiddlyWiki into NoteSelf?  And if so, how to do this?  Thanks!

**Comment by danielo515** [comment]
I don't see any reason why this may not work. Just drag and drop your old file into the NoteSelf online version opened on your browser

**Comment by danielo515** [comment]
I'll close this issue since the question is answered. If you need something else feel free to comment.
