### ISSUE TITLE
Firefox 57

### ISSUE THREAD

**Issue by LindyBalboa** [NoteSelf/NoteSelf.github.io#47]
Not so much an issue, but a qeustion. Is it known how NS will play with FF57? Since it uses PouchDB I feel it may avoid the saving issue that vanilla TW5 has, but I haven't actually used it nor do I know the internals. Could a contributor comment on this?

**Comment by danielo515** [comment]
I just tried it on firefox 57 and it works. At least the online version does: https://noteself.github.io/online/

**Comment by darinwick** [comment]
I've been using both the online and offline versions in Firefox 57 with no trouble.
