### ISSUE TITLE
"Save Empty" saves a file that gives "Internal JavaScript Error" when opened

### ISSUE THREAD

**Issue by darinwick** [NoteSelf/NoteSelf.github.io#48]
When I use "Save Empty" from the Download tab in the TiddlyPouch tab of the Control Panel, it downloads a file which, when opened, gives: 

> Internal JavaScript Error
> Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
> ReferenceError: $TPouch is not defined

My goal is to host a NoteSelf instance on my own server that automatically connects to the correct CouchDB server so I (and friends and family) can navigate to "mydomain/wiki" and have everything loaded instead of needing to enter database info every time we open NoteSelf on a new computer.  If there's a better (or more effective) way to do that, please let me know!

**Comment by darinwick** [comment]
I compared a working "offline" version of NoteSelf with the version created by "Save Empty" and found that the latter was missing PouchDB.  Copied that in, and it seems to work fine.

**Comment by danielo515** [comment]
Yes, the bug is isolated.
I'm not sure why pouchdb is not being included. Probably some issues with templates and how tiddlywiki exports the tiddlers. I'll try to fix it to allow people generate "snapshots" of their wikies.

**Comment by danielo515** [comment]
This should be fixed after the new release finishes

**Comment by darinwick** [comment]
Hey, it works now!  Nice fix; thank you!
