### ISSUE TITLE
No synchronisation

### ISSUE THREAD

**Issue by sdelaye** [NoteSelf/NoteSelf.github.io#5]
Hello.
Pouchdb on my own server (it works for me, it should work for you too): 
curl -X GET http://mymo:mymo@myprivatepad.fr:5984/mymo/
{"db_name":"mymo","doc_count":1,"doc_del_count":0,"update_seq":2,"purge_seq":0,"compact_running":false,"disk_size":8283,"data_size":285,"instance_start_time":"1483140014779458","disk_format_version":6,"committed_update_seq":2}

In NoteSelf:

===SYNC Error starting==={
    "status": 0,
    "name": "unknown"
}

Parameters in TiddlyPouch tab:
CouchDB URL:   http://myprivatepad.fr:5984
Database: mymo
user: mymo

When I click only, ask for login/password: "mymo" /  "mymo"
Any Idea ?

**Comment by danielo515** [comment]
Hello @sdelaye, thank you for trying Noteself. 

I didn't make any investigation yet, but I guess that several things are happening:

- you're trying to access an http server from an https origin. Browsers prevent this kind of things. Both the server and the client should speak http or https, never mix. 
- if you are using a standard version of couchdb then CORS is not activated by default. You have to activate it for being able to access your database server from online version of Noteself. Let me look for instructions about how to setup CORS. 

In any case, you can create a free account on cloudant which makes all this things easier.

**Comment by sdelaye** [comment]
Hello,

1- I downloaded the empty html file: is it consider as http or https ?

2- CORS is alreadyt activated (option in the config file).

3- I created a cloudant account. It said XMWHttpRequest error code: 0
CouchDB URL: http://mymo.cloudant.com/ (I tried https )

Remote database name: mymo
What 's wrong ?

Can you send an exemple of config ?

**Comment by danielo515** [comment]
Hello @sdelaye 

1. The empty file is considered http, so it should work with the http server.
1. About enabling CORS on your own server, could you please try to follow this small guide? https://pouchdb.com/getting-started.html#enabling_cors Basically this part:
  ```
    npm install -g add-cors-to-couchdb
    add-cors-to-couchdb
  ```
    Or if your database is not at 127.0.0.1:5984:
  ```
  $ add-cors-to-couchdb http://me.example.com -u myusername -p mypassword
  ```

Cloudant also requires you to enable CORS. It is very straighforward:

![image](https://cloud.githubusercontent.com/assets/2270425/21626199/141f5638-d210-11e6-8276-f36d19b1b361.png)

If any of those makes noteself work for you I will try to reproduce it myself.
Regards

**Comment by sdelaye** [comment]
Solved ! It works with those guidelines. Thank you very much.

**Comment by danielo515** [comment]
Dear @sdelaye, you're welcome 
I'm curious about if both servers are now working? Cloudant and your custom one?

**Comment by sdelaye** [comment]
Hello,

Yes, both servers are now working.

But maybe I should work a little bit more with mine to secure the 
server: https, limited grants...

At the moment, it's open bar !

Best,

Stephane
