### ISSUE TITLE
Not loading again after initial configuration

### ISSUE THREAD

**Issue by mortuosplango** [NoteSelf/NoteSelf.github.io#50]
In Chrome on a mac and also with chromium and firefox on android, when I configure the synchronisation with my cloudant service it initially syncs fine, loading all of the ca. 30 tiddlers. I can make changes and it syncs them back just fine. When I reload the tab, or try to open noteself in another tab, noteself just shows the loading animation and in the console displays this:

```
Navigated to https://noteself.github.io/online/
(index):267 Injecting  3  startup tiddlers into tw
(index):10362 Uncaught (in promise) SyntaxError: Unexpected token $ in JSON at position 0
    at JSON.parse (<anonymous>)
    at $tw.Wiki.readPluginInfo ((index):10362)
    at Object.$tw.boot.startup ((index):11309)
    at (index):11485
    at Object.$tw.boot.decryptEncryptedTiddlers ((index):10685)
    at Object.$tw.boot.boot ((index):11483)
    at (index):278
    at <anonymous>
```

When I hard-reload I get a JS error as well (which is just the same error I suppose):

> Internal JavaScript Error
> Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
> Uncaught SyntaxError: Unexpected token $ in JSON at position 0

Noteself is really great btw (when it works, it works really well) :)

**Comment by danielo515** [comment]
Hello @mortuosplango 
I never faced that error. I admit that the booting mechanism could have better error handling.
Does any of your tiddlers include JSON data ? Or have you installed any plugin ? To me it seems like an error raised by TW trying to parse a bad formatted plugin.

If you can share your list of plugins and/or tiddlers that would be supper.

Regards

**Comment by mortuosplango** [comment]
Hey,

I deleted a lot of tiddlers that I thought were not the problem and then wanted to send you the remaining set, but ofc it turns out one of them actually was... even though they were just shopping list entries (e.g., title: "milk", tag: "groceries"). D'oh. 

I tried to install the checklist plugin ( https://github.com/tgrosinger/tw5-checklist ) but didn't manage to, deleted the tiddlers and it worked afterwards, so I think that probably wasn't the cause.

It still won't load on firefox on android though because probably I didn't manage to delete the browser storage - any chance to extract it for analysis?

Anyways, all other browsers work again now. Will let you know if it happens again.

**Comment by danielo515** [comment]
> but ofc it turns out one of them actually was... even though they were just shopping list entries (e.g., title: "milk", tag: "groceries"). D'oh.

Do you have a copy of such tiddler ?

> It still won't load on firefox on android though because probably I didn't manage to delete the browser storage - any chance to extract it for analysis?

Not sure how works on firefox, but on chrome you can remotely connect to the browser's device. That way we can inspect it, but again, not sure about firefox.

**Comment by mortuosplango** [comment]
Hey, I don't have a copy of them. I tried to recreate them but it's been working ever since. When it next stops working I'll make sure to investigate more. I'll close that for now as it's working now.
