### ISSUE TITLE
Tried loading a plugin from another tiddlywiki, I only get an error now

### ISSUE THREAD

**Issue by RGKaizen** [NoteSelf/NoteSelf.github.io#51]
Hi, I tried importing a theme from another tiddlywiki to try it out, but it didn't bring the refernece with it. Now my Tiddlywiki is in a broken state and I don't know how to fix it.

I only get this on the page:
Undefined widget 'muuri'

How can I update my tiddlies outside of the ui?

**Comment by RGKaizen** [comment]
So I managed to fix this by deleting the TP_CONFIG pooch indexedDB from within Chrome. I'm glad this worked without breaking my notes. Is it safe to say that TP_CONFIG can be reset in cases of misconfiguration?

**Comment by danielo515** [comment]
Hello @RGKaizen , glad you solved your problem

> Is it safe to say that TP_CONFIG can be reset in cases of misconfiguration?

Yes it is. It is automatically generated, and it only persist your database selection preferences and some other small configurations, nothing very importatn.

Regards
