### ISSUE TITLE
Error executing boot module

### ISSUE THREAD

**Issue by cloudyangel** [NoteSelf/NoteSelf.github.io#53]
When I am going to visit my notebook Online, it shows:

_Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Error executing boot module $:/plugins/felixhayashi/tiddlymap/js/lib/utils/tmap_
---
I realized that it caused by the incompleted installation of plugin_tiddlymap.
I have just install a part of the plugin_tiddlymap.

Now, I cannot get access to my notebook online, neither to recover it nor create a new notebook ?
Would you please check this issue ?
thanks a lot.

**Comment by cloudyangel** [comment]
Total warning is as blow:

Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Error executing boot module $:/plugins/felixhayashi/tiddlymap/js/lib/utils/tmap: "Cannot find module named '$:/plugins/felixhayashi/vis/vis.js' required by module '$:/plugins/felixhayashi/tiddlymap/js/lib/utils/tmap', resolved to $:/plugins/felixhayashi/vis/vis.js" undefined
close

**Comment by cloudyangel** [comment]
When I get access to _advanced settings_ of Chrome browser, I find the clear cache function would help to clear all contents on noteself.github.io; 
I can start from the beginning again now.
But I lost all data.

**Comment by cloudyangel** [comment]
I guess if I don't clear the database in cloudant, the data could be recovered.
For reference.

**Comment by danielo515** [comment]
Hello @cloudyangel 
Sorry to hear that you have faced this problem. We definitely need a safe mode to recover from situations like this.
If you have your tiddlers saved on a remote database then they are not lost. However, if the plugin has been saved to the remote database too then when you finish the synchronization you will have the same problem again.
The solution requires you going to your cloudant database and deleting the tiddlymap plugin tiddler. It should not be hard, let me know if you need help with that.

Regards

**Comment by cloudyangel** [comment]
Thanks, @danielo515 
appreciated your quick response.  I don't have important data in the database for the moment because I'm a beginner of TW5. NS, so that I have cleared all the data now.

**Comment by danielo515** [comment]
Hello again @cloudyangel
Glad to hear that. If you ever find the same problem again feel free to reopen this issue
