### ISSUE TITLE
Type field unselectable

### ISSUE THREAD

**Issue by mikenick42** [NoteSelf/NoteSelf.github.io#55]
When I try to select a type for my tiddlers the formatting of the menu is messed up and I'm not able to select anything. I had been adjusting some settings, but I'm not sure what would have done this.

![Screenshot of problem](https://i.imgur.com/rDw9Ksq.jpg)

**Comment by danielo515** [comment]
Do you mean  that you can not click on the options or that you can not type on the field?

**Comment by mikenick42** [comment]
I can not click any of the options.

For some background, I'm using a couchdb backend to sync between my laptop and the NoteSelf app on Android. I used to be able to click the options, and each one (HTML, Plain text, TiddlyWiki 5, etc) appeared on its own line. But after changing some settings, and possibly accidentally clicking the garbage can, I get the screenshot above both on a web browser and the app.

So I think it's probably user error that somehow messed up the database. I was just hoping there was a way to fix it that was easier than manually exporting all my tiddlers to a new instance.

**Comment by mikenick42** [comment]
On my laptop I'm using Firefox. Chrome gives me a simple Login Failed message when I try to log in to the database. When I open it in Chromium I get two errors and can't connect to the database.

1) "Error retrieving skinny tiddler list: TypeError: Cannot read property 'length' of undefined"
2) "Sync error while processing '$:/StoryList': {"status":500,"name":"indexed_db_went_bad","message":"unknown","reason":"Failed to open indexedDB, are you in private browsing mode?"}"

The dropdown menus seem to be working the way they're supposed to though.

In Firefox, I'm not sure what to look for exactly. I can post a screenshot, but I can't be sure it would even be looking at the right thing.

**Comment by mikenick42** [comment]
I'm not sure what happened, but I ended up transferring everything to a new database and it seems to be working now.

**Comment by danielo515** [comment]
Hello @mikenick42 , glad to hear that at the end it is working for you.
Probably the problem was some tiddler hardcoded to the html file you were using, that's why moving to a fresh instance fixed the problem. The tiddler were not on the DB and that's why you were able to fix it by moving your tiddlers to a new db.

Glad to hear the good news.
