### ISSUE TITLE
Need instructions to remove ALL NoteSelf data from browser (e.g., a "factory reset")

### ISSUE THREAD

**Issue by rmunn** [NoteSelf/NoteSelf.github.io#56]
I tried earlier this week to set up a CouchDB server on my laptop (running Linux) and use it as storage for NoteSelf. I got something wrong with user permissions, and the first connection failed... but now every time I go to https://noteself.github.io/online/ I get an immediate error popup:

> syncer-browser - 10:57:24 24 3 2018 (count: 2)
> Error retrieving skinny tiddler list: TypeError: Cannot read property 'length' of undefined

(The count on that error keeps going up: right now it's 15, yesterday when I forgot to close the NoteSelf tab the count went up into the 100,000 range).

Then underneath that error, I got another error:

> syncer-browser - 10:54:24 24 3 2018
> Sync error while processing '$:/StoryList': InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

A quick look at the Javascript console revealed that all of these problems apparently stem from PouchDB not being able to store any data: one of the first errors found in the Javascript console, before the rest of the errors, is:

> $:/core/modules/utils/logger.js:30 TiddlyPouch:config: Persist config to DB - ERROR n {status: 500, name: "indexed_db_went_bad", message: "unknown", error: true, reason: "QuotaExceededError"}

I'll copy the full text from the Javascript console and put it at the bottom of this issue report so that you'll be able to see all the error messages — but that one seems the most relevant to me since I know I configured my CouchDB server incorrectly the first time (I hadn't given permission to the user account that I'm using for NoteSelf). So if that config is stored somewhere in my browser, I need to get rid of it to reset NoteSelf back to defaults. (Using a different browser produces no errors and I can use NoteSelf normally).

I've tried going to the Application tab of the developer console and clearing all storage for the noteself.github.io site, then refreshing. That hasn't helped; the same set of errors persists. Which is very strange: I would have expected that clearing all site data would have cleared whatever incorrect configuration is still lingering. So perhaps I'm wrong about it being a lingering CouchDB config string. At any rate, I'd like to try to perform a "factory reset", and if simply clearing all site data on the Application tab isn't enough, then I need instructions on what else to do.

Below is the full Javascript console (from about a minute after loading the tab; if I waited longer, there would be even more errors, but they'd be copies of the previous errors). Also, if you need more info, I do Web development for my job, so you can ask me for any technical details and I'll understand what you want and be able to give them to you.

```plaintext
(index):275 Something went wrong during plugin injection  n {status: 404, name: "not_found", message: "missing", error: true, reason: "missing"}
(index):280 Allowing TW boot itself....
$:/core/modules/utils/logger.js:30 TiddlyPouch:config: Initializing config module
$:/core/modules/utils/logger.js:30 TiddlyPouch:config: Config read from DB - ERROR n {status: 404, name: "not_found", message: "missing", error: true, reason: "missing"}
$:/plugins/danielo515/tiddlypouch/startup/config.js:16 No tiddler config, using default
$:/core/modules/utils/logger.js:30 TiddlyPouch:config: Persist config to DB - ERROR n {status: 500, name: "indexed_db_went_bad", message: "unknown", error: true, reason: "QuotaExceededError"}
$:/core/modules/utils/logger.js:30 TiddlyPouch:config: Configuration startup finished {debug: {…}, selectedDbId: "MyNotebook", databases: {…}}
$:/core/modules/utils/logger.js:30 PouchStartup: Client side dbs created
2(index):54 Database has a global failure DOMException
S @ (index):54
h.onabort @ (index):55
$:/core/modules/utils/logger.js:30 PouchStartup: Something went wrong during index creation n {status: 500, name: "indexed_db_went_bad", message: "unknown", error: true, reason: "QuotaExceededError"}
$:/core/modules/utils/logger.js:30 DbStore:MyNotebook: Error getting tiddler $:/StoryList from DB DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at ht (https://noteself.github.io/online/:55:15986)
    at Te.e._get (https://noteself.github.io/online/:55:24216)
    at Te.<anonymous> (https://noteself.github.io/online/:58:1428)
    at Te.<anonymous> (https://noteself.github.io/online/:54:26515)
    at Te.<anonymous> (https://noteself.github.io/online/:54:887)
    at https://noteself.github.io/online/:54:25939
    at new Promise (<anonymous>)
    at Te.<anonymous> (https://noteself.github.io/online/:54:25858)
    at Te.get (https://noteself.github.io/online/:54:887)
    at DbStore.getTiddler ($:/plugins/danielo515/tiddlypouch/DbStore.js:12:1740)
$:/core/modules/utils/logger.js:30 PouchStartup: Error retrieving StoryList or DefaultTiddlers
$:/core/modules/utils/logger.js:30 PouchStartup: Client side dbs initialized
$:/core/modules/utils/logger.js:30 syncer-browser: Retrieving skinny tiddler list
$:/core/modules/utils/logger.js:30 DbStore:MyNotebook: DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at ht (https://noteself.github.io/online/:55:15986)
    at Te.e._get (https://noteself.github.io/online/:55:24216)
    at Te.<anonymous> (https://noteself.github.io/online/:58:1428)
    at Te.<anonymous> (https://noteself.github.io/online/:54:26515)
    at Te.<anonymous> (https://noteself.github.io/online/:54:887)
    at https://noteself.github.io/online/:54:25939
    at new Promise (<anonymous>)
    at Te.<anonymous> (https://noteself.github.io/online/:54:25858)
    at Te.get (https://noteself.github.io/online/:54:887)
    at vr (https://noteself.github.io/online/:57:11884)
$:/core/modules/utils/logger.js:30 syncer-browser: Error retrieving skinny tiddler list: TypeError: Cannot read property 'length' of undefined
    at eval ($:/core/modules/syncer.js:211)
(index):54 Database has a global failure DOMException
S @ (index):54
h.onabort @ (index):55
$:/core/modules/utils/dom/http.js:65 OPTIONS https://noteself.github.io/online/ 405 ()
exports.httpRequest @ $:/core/modules/utils/dom/http.js:65
PutSaver @ $:/core/modules/savers/put.js:28
exports.create @ $:/core/modules/savers/put.js:108
(anonymous) @ $:/core/modules/saver-handler.js:122
(anonymous) @ (index):10087
$tw.utils.each @ (index):9393
$tw.modules.forEachModuleOfType @ (index):10086
SaverHandler.initSavers @ $:/core/modules/saver-handler.js:120
SaverHandler @ $:/core/modules/saver-handler.js:30
exports.startup @ $:/core/modules/startup.js:115
$tw.boot.executeNextStartupTask @ (index):11378
asyncTaskCallback @ (index):11357
(anonymous) @ $:/plugins/danielo515/tiddlypouch/startup/pouch.js:14
Promise.then (async)
exports.startup @ $:/plugins/danielo515/tiddlypouch/startup/pouch.js:14
$tw.boot.executeNextStartupTask @ (index):11384
asyncTaskCallback @ (index):11357
(anonymous) @ $:/plugins/danielo515/tiddlypouch/startup/config.js:16
Promise.then (async)
exports.startup @ $:/plugins/danielo515/tiddlypouch/startup/config.js:16
$tw.boot.executeNextStartupTask @ (index):11384
$tw.boot.executeNextStartupTask @ (index):11382
$tw.boot.executeNextStartupTask @ (index):11382
$tw.boot.startup @ (index):11335
(anonymous) @ (index):11485
$tw.boot.decryptEncryptedTiddlers @ (index):10685
$tw.boot.boot @ (index):11483
_boot @ (index):11492
(anonymous) @ (index):11502
$:/core/modules/wiki.js:152 [Violation] 'setTimeout' handler took 106ms
(index):54 Database has a global failure DOMException
S @ (index):54
h.onabort @ (index):55
sw.js:1 Uncaught (in promise) DOMException: Quota exceeded.
$:/core/modules/utils/logger.js:30 syncer-browser: Dispatching 'save' task: $:/StoryList
$:/core/modules/utils/logger.js:30 syncer-browser: Sync error while processing '$:/StoryList':
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
$:/core/modules/wiki.js:152 [Violation] 'setTimeout' handler took 67ms
```

**Comment by danielo515** [comment]
Hello @rmunn , thanks for using NoteSelf and for reporting your problems.
Your problem seems to be related to disk quota. As far as I know, chrome has about 10% reserved for local-storage, so if you are low in space that can be the problem.
In any case, the following screenshot should help you deleting the unnecessary databases. It describes how to delete one database, but probably yo can delete all at once. Since you are already familiar about how to opening the developer console I'll skip that part.

1. Make sure you have opened the NoteSelf website
2. Open Chrome developer tools
3. Follow the instructions on the screenshot below
![deletedbs](https://user-images.githubusercontent.com/2270425/37894184-b4b883d0-30dd-11e8-9a2d-8b29c25c2833.jpeg)

Let me know if this instructions fixes your problem.
Regards

**Comment by rmunn** [comment]
I'd already tried deleting the database with no success, but I hadn't realized that being low on free space would cause Chrome to deny local storage like that. I freed up several gigabytes of space, and the problem went away. Thanks for the help.

**Comment by danielo515** [comment]
Hello @rmunn,

Glad to hear that! Yes, as far as I know chrome reserves a 10% of your free disk space, so the less disk space, the less available. 

Regards
