### ISSUE TITLE
Can not delete database

### ISSUE THREAD

**Issue by sdelaye** [NoteSelf/NoteSelf.github.io#6]
Hello,
When I click "delete database", it does'nt work and display a message:
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: $TPouch.database.destroy is not a function
The browser is firefox 50.1.0
The same appears with Chrome

**Comment by danielo515** [comment]
Thank you for the report @sdelaye , I'll take a look into it
