### ISSUE TITLE
Local storage is deleted

### ISSUE THREAD

**Issue by rrblocker** [NoteSelf/NoteSelf.github.io#62]
I'm having an issue with local storage persistence using NoteSelf in the latest Firefox Quantum 60.0.1 (64bit) on Ubuntu 18.04. This is a fresh install. I have my own CouchDB repository running v.2.1.1 that I use for synchronizing. I can synchronize fine by entering and saving the Notebook Name, CouchDB URL, and Remote database name in the sync configuration. However, every time I restart my browser and open NoteSelf again, it returns to the GettingStarted tiddler and all the sync configuration settings are gone.

I sometimes get this Javascript error:
   "NotFoundError: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened."

I have checked the path to the local storage, and I can see that it stays there when I quit Firefox, but is deleted when I restart Firefox and open NoteSelf which is at a local file:/// URL.
 
I have never had this problem before. Storage persists and I can synchrnize on two other older laptops running Ubuntu 16.04 and Firefox 60. It also works on Chromium on Ubuntu 18.04. 

Any ideas what could be going on?

**Comment by danielo515** [comment]
Yes, I have a couple, have you checked this section of the Inportant information section on the control panel ?
> Important information
>Local databases are grouped by domain. If you work with your wiki from a file then that particular file will not be able to access any of the databases created by any wiki accessed online. If you want to sync databases between a wiki served by http and a local wiki you have to use some couch backend or export and import the database

Does that describe your problem ?
Also note that different file names are also considered different domains.

Regards

**Comment by rrblocker** [comment]
Unfortunately, it appears not to apply. I am only trying to access the wiki from a file on both systems. The file is in the same path on both laptops. It is in a folder shared using ownCloud. The URL is "file:///home/username/ownCloud/enotes/tiddlywiki/notes.html"

I just tried again: after clearing all Firefox cookies and local files, then adding the information into the wiki settings, I could sync with my ChouchDB and see all the wiki pages. However, when I quit Firefox and started it again, the settings were gone.

**Comment by danielo515** [comment]
Hello @rrblocker , that is quite odd.
Have you tried to use the same file on other browser ? Just to isolate if the problem is tied to firefox.

**Comment by rrblocker** [comment]
Hi @danielo515. Yes. It works on Chromium on the same file on the same Ubuntu 18.04 laptop where it fails on Firefox.

**Comment by danielo515** [comment]
That's weird.
Could you please show me an screenshot of the Firefox console?
