### ISSUE TITLE
Possible to upgrade to TW 5.1.17 now?

### ISSUE THREAD

**Issue by rmunn** [NoteSelf/NoteSelf.github.io#63]
https://github.com/NoteSelf/NoteSelf.github.io/issues/30 mentions locking the TW version that NoteSelf uses to 5.1.14 because of some changes made in TW after that point (such as https://github.com/Jermolene/TiddlyWiki5/commit/e3544ff3c26256999992ba1ebae5b911c31153f2) that would adversely affect NoteSelf. But in the further dicussion of that commit, there's a note that this change was reverted in https://github.com/Jermolene/TiddlyWiki5/commit/cf9085b5cecd794030a0fc3e4d9673db31a5d85e. Does this mean that it would now be possible to update NoteSelf to use TW 5.1.17? Or are there any *other* changes between 5.1.14 and now that would make an upgrade to 5.1.17 too difficult?

I ask because I have a wiki that could benefit from some of the changes introduced in 5.1.15 (specifically, the addition of the `tiddler`, `field` and `index` attributes to the `SetWidget`) and I'd like to be able to use those changes.

**Comment by danielo515** [comment]
There is a noteself edition build with the latest version of tiddlywiki for testing purposes.
You can check it out at https://noteself.github.io/edge/ to see how good or how bad does it work for you.

Note that many plugins may have an upredictable behavior

**Comment by danielo515** [comment]
We are already on 5.1.21, and we plan to upgrade to 5.1.23 when it gets the time
