### ISSUE TITLE
Button to force offline mode.

### ISSUE THREAD

**Issue by chanilino** [NoteSelf/NoteSelf.github.io#69]
I have my couchdb server behind an vpn in my home network. I configure Noteself with the vpn ip. If I reload noteself without being connected to the vpn, The noteself remains empty, like loading, waiting for a response of the couchdb that never comes. This state keep for minutes.

I think we can put a button to force offline mode to resolve this issue, or something like a configurable timeout to pass offline mode. If we don't have response in x seconds, we go to offline mode.

Thanks, 
I love this new flavour of tw5.

**Comment by danielo515** [comment]
What do you mean exactly with empty? The loading screen? Or that it works but it has no content?
The sync happens asynchronously, this means that it should not stop anything from working, even if it is not able to reach the server.

**Comment by chanilino** [comment]
Sorry, I dont use that vpn anymore, so I cannot reproduce the problem, now. Noteself is working well, for me now, so I can close the issue.
