### ISSUE TITLE
Problem when loading

### ISSUE THREAD

**Issue by sdelaye** [NoteSelf/NoteSelf.github.io#7]
Hello.
I downloaded the latest version (With delete database option, thanks !!) and I have trouble for loading from an http server (No problem when empty.html is on my harddrive). 
It takes more than 20mn when it's on my apache webserver.
It tested on another server and same problem. There are plenty of http access.
Please help.

**Comment by danielo515** [comment]
Hello,
The proper way of downloading an empty version is from Noteself site. Could you please try to download it from there and check with that file ?

If the problem persist, could you open the chrome developer tools and take an screenshot ?

**Comment by sdelaye** [comment]
I downloaded a new empty file. Looks working. I don't know what happened 10 days ago.
Sorry.

**Comment by danielo515** [comment]
Don't worry @sdelaye, you're welcome.

Glad it works now.
