### ISSUE TITLE
Confusion of Deleting database

### ISSUE THREAD

**Issue by liyzcj** [NoteSelf/NoteSelf.github.io#71]
As discussed in forum: [https://forum.noteself.org/t/remove-notebook/195/7](url)
After delete a database, the name of database should be removed from list.

The prompt of Delete button is reloading Noteself quickly, but if you reload the page after delete a database but don't change database in list, this database will be created again.

**Comment by danielo515** [comment]
Thanks for opening the issue @liyzcj .
This same issue has been reported on tiddlypouch repository here:
https://github.com/danielo515/tiddlypouch#82

**Comment by danielo515** [comment]
This has been fixed and released yesterday.
