### ISSUE TITLE
Where is the intro texts

### ISSUE THREAD

**Issue by twMat** [NoteSelf/NoteSelf.github.io#8]
Silly question but where in this github repository is actually the text that one sees on the NoteSelf frontpage? I.e where you talk about the NoteSelf features, FAQ etc.

Note that some of the files are apparently too big to show in the github UI, so maybe it is in one of those:

![image](https://cloud.githubusercontent.com/assets/4534056/24391086/37bf55e8-138d-11e7-8dfb-271f213b28ac.png)

**Comment by danielo515** [comment]
Dear @twMat 

Thank you for opening an issue on NoteSelf repo.

Currently, all the NoteSelf repo has is the index page. This is because the code that generates such page is not tidy enough and it's too tied to my computer's filesystem, so it will not work on other people's computer. 

I have the intention to fix this situation and also made the build of the index page an automatic process.

**Comment by twMat** [comment]
>Currently, all the NoteSelf repo has is the index page. 

Ok, if you want to, and remember, please post a note in this thread when you eventually fix it. I'm asking because I have some tweaks to the texts.

Thanx @danielo515

**Comment by danielo515** [comment]
Dear @twMat ,

I just uploaded the code that powers NoteSelf to the develop branch.
I also added a travis-ci file that builds the entire website:
 - index page (the presentation one)
 - online version ( minified code and offline capabilities )
 - development version. This one has the code unminified. Good to play with

So, to make pull requests, navigate the tiddlers and edit the text that is used to build the website you have to go to the develop branch. Make sure to make the pull request to the develop branch as well.

Now you can play with it as long as you want!!!

**Comment by twMat** [comment]
Sorry, but I don't understand. This is what I get:

![image](https://cloud.githubusercontent.com/assets/4534056/24826407/ca9a2478-1c35-11e7-9338-6e4c5e71101a.png)

**Comment by danielo515** [comment]
Dear Mat,

You are on the master branch. The dev folder of the master branch is just like the online version but with the plugin code non minified.

I mean the develop **branch** . Do you see the selection field jus right below the code tab ? Click on it and select the develop branch.

Regards

**Comment by twMat** [comment]
@danielo515 - thanks, but please provide a link instead. Let's pretend I wish to edit the first word here, please provide a link to this:

![image](https://cloud.githubusercontent.com/assets/4534056/24827784/d9f5d082-1c50-11e7-8d02-d61a01f03872.png)

**Comment by danielo515** [comment]
Here is the link ( hope you don't get the mobile version )

https://github.com/NoteSelf/NoteSelf.github.io/blob/develop/wiki/tiddlers/Presentation.tid

In any case, I'll make the develop branch the default one, so it will be easier to find any tiddlers

**Comment by twMat** [comment]
Thanx!

>In any case, I'll make the develop branch the default one, so it will be easier to find any tiddlers

Yes, please make it easy for contributors ;-)

**Comment by danielo515** [comment]
It's already done.

Thank you Matt for keeping the interest.
May the issue be closed ?
