### ISSUE TITLE
Export does not work. only whole wiki as json - no html or others

### ISSUE THREAD

**Issue by christofbuerger** [NoteSelf/NoteSelf.github.io#9]
Dear Danilo,

I love noteself. Yet there are two major issues - 
export of tiddlers whereever tried leads always to the export of a json file containing all tiddlers. it is not possible to export specific tiddlers. and it is not possible to export as html or tid or csv.

second - import of the created json does not work. The Tags are ignored. I suppose the format is not right tags: ["Tag1", "Tag2"] should be tags: "Tag1 Tag2"

Would love if you can fix that somehow. Would make the tool even greater than it is already :-)

Best Regards
Christof

**Comment by danielo515** [comment]
Dear @christofbuerger 

Thank you very much for using NoteSelf and giving feedback to the project.
The problem you mentioned is a known issue. The export feature was created as a fast ad-hoc solution for people that wanted to opt-out from NoteSelf, or for those that want a backup of their database. For this reason, I did not worked more on building a proper system to "generate" a tiddlywiki from a noteself database.

About the second problem, I agree that the exported JSON format should be TW compatible. However, I really feel that who is doing things wrong is tiddlywiki. It's reasonable to expect that a list of tags can be provided as an array. There is an issue about this on TW repository: jermolene/tiddlywiki5#2755 In any case, probably fixing the second problem will make the first problem not so big, so I will put the second problem higher on the list

Thanks for the report

**Comment by christofbuerger** [comment]
Thank you Danielo. That would be great! :-)
Have a nice weekend
